apiVersion: v1
kind: Service
metadata:
  name: x-skynet-agent
  namespace: x-skynet
  labels:
    app.kubernetes.io/name: x-skynet-agent
    app.kubernetes.io/component: agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: x-skynet-agent
    app.kubernetes.io/component: agent
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
